sudo: required

language: generic

dist: trusty

os: linux

services:
  - docker

before_install:
  # update packages
  - sudo apt-get update

  # allow write access to /usr/local/bin
  - sudo chown -R $(whoami) /usr/local/bin

  # emit current docker-compose version
  - docker-compose --version

  # emit current docker-compose config
  - docker-compose config

  # use specific docker-compose version
  - curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

  # emit new docker-compose version
  - docker-compose --version

  # build and start services
  - docker-compose build --force-rm --no-cache

  # list running containers
  - docker-compose ps

script:
  # install composer packages
  - docker-compose run -T --rm composer install

  # install npm modules
  - docker-compose run -T --rm node yarn install

notifications:
  slack: itpinoynz:0eGHUYzUtWlarK8WNxMbNAcH
